services:
  db:
    image: postgres:17
    container_name: odoo_db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo_app
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo_data:/var/lib/odoo
      - ../ic_urfu_module:/mnt/extra-addons/ic_urfu_module
      - ./odoo.conf:/etc/odoo/odoo.conf
    restart: always

volumes:
  db_data:
  odoo_data:
